### ISSUE TITLE
Determine the best way to ascertain a diffbase for a Travis "push" build

### ISSUE THREAD

**Issue by dhermes** [dhermes/ci-diff-helper#1]
There are a two ways one might go, in order of desirability:

1. Use `TRAVIS_COMMIT_RANGE`. Though this is problematic for "push" builds. It is populated with `${START}...${FINISH}`. `${FINISH}` is straightforward: the `HEAD` commit in the branch (also `TRAVIS_COMMIT`). However `${START}` is just the SHA of `HEAD` in the last "push" build that Travis ran. In theory this works just fine, but if there are rebases / force pushes / race conditions, bad things can happen.
1. Assume the commit came from a merged PR and get the base from that PR
1. Use the Travis API (http://api.travis-ci.org/repos/{org}/{repo}/builds?event_type=push`) to find the last build and then get the `HEAD` commit in that build. The `builds` request returns a list, so one could get the commit (parsed JSON) via `resp[0]['commit']`.

In the case that we assume it came from a PR, we can:

1. Parse the PR ID from the `HEAD` commit message (then verify it using the GitHub API `https://api.github.com/repos/{org}/{repo}/pulls/{pr-id}` which will have a key called `merge_commit_sha`, also in the response `resp['base']['sha']` will give us our base.)
1. Use the unpublished `https://github.com/{org}/{repo}/branch_commits/{sha}` API (which spits out an SVG with a structured `<li class="pull-request">` containing an anchor with the PR ID)

**Comment by dhermes** [comment]
FYI @jonparrott was [very right][1] about rate-limiting:

```
Traceback (most recent call last):
  File "scripts/do_it.py", line 16, in <module>
    value = getattr(config, prop)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/ci_diff_helper/travis.py", line 277, in base
    self._base = _push_build_base(self.slug)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/ci_diff_helper/travis.py", line 208, in _push_build_base
    return _get_merge_base_from_github(slug, start, finish)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/ci_diff_helper/travis.py", line 178, in _get_merge_base_from_github
    response.raise_for_status()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.github.com/repos/dhermes/ci-diff-helper/compare/38ebf17f978c...37cbb10a32e6
```

Though it's per-IP, so some jobs are OK. In the case of failure, I [added support][3] for actually printing out the GitHub rate-limiting headers. [Here it is][2] in action:

```
Request all good but here are the headers anyway.
    X-RateLimit-Remaining: 4953
        X-RateLimit-Limit: 5000
        X-RateLimit-Reset: 1475955246
```

[1]: https://travis-ci.org/dhermes/ci-diff-helper/builds/166073849#L179
[2]: https://travis-ci.org/dhermes/ci-diff-helper/builds/166093560
[3]: https://github.com/dhermes/ci-diff-helper/blob/d0654bec09a67b7a4c10657d72412788e556d83f/ci_diff_helper/_github.py#L73

**Comment by dhermes** [comment]
I did some fairly extensive testing of all 3 merge types (merge, squash-merge and rebase) and nothing seemed to go wrong. See #3, #4, #5, #6, #7. Also, after the fact I did a squash merge back to the very beginning and the GitHub API got the correct diffbase: https://travis-ci.org/dhermes/ci-diff-helper/builds/166542863
